version: '2'
services:
  proxyserver:
    container_name: proxyserver
    build:
      context: .
    links:
      - metadataserver:metadata
    ports:
      - 8181:8181
    environment:
      METADATA_PORT: tcp://metadata:8121

  elasticdb:
    image: elasticsearch:2.4
    container_name: elasticdb
    ports:
      - 9200:9200
      - 9300:9300

  metadatadb:
    image: postgres
    container_name: metadatadb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pacifica_metadata
      POSTGRES_USER: metadata
    ports:
      - 5432:5432

  metadataserver:
    image: pacifica/metadata
    container_name: metadataserver
    links:
      - metadatadb:postgres
      - elasticdb:elasticdb
    ports:
      - 8121:8121
    environment:
      ELASTICDB_PORT: tcp://elasticdb:9200
      POSTGRES_ENV_POSTGRES_DB: pacifica_metadata
      POSTGRES_ENV_POSTGRES_USER: metadata
      POSTGRES_PORT_5432_TCP_ADDR: postgres
      POSTGRES_PORT_5432_TCP_PORT: 5432
      POSTGRES_ENV_POSTGRES_PASSWORD: password
